#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export EDITOR='vim'
export VISUAL='vim'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias dev='mosh -6 devvm25838.prn1.facebook.com'
alias sz="source ~/.zshrc"
alias ez="e ~/.zshrc"
alias gs='git status --short -b'
source ~/.bash/_bash_spark
