#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export EDITOR='vim'
export VISUAL='vim'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias sz="exec zsh"
alias ez="e ~/.zshrc"

## git overrides
alias gs='git status --short -b'
alias ga='git add'

## tmux overrides
alias tls='tmux list-sessions'
alias tatt='tmux attach-session -t '

## i need to see what is in a directory when i get there
function cd {
  new_directory="$*"
  if [ $# -eq 0 ]; then
    new_directory=${HOME};
  fi;
  builtin cd "${new_directory}" && ls -pGF
}

# env vars
export PDSH_SSH_ARGS_APPEND='-q -o StrictHostKeyChecking=no'

# Source Prezto.
if [[ -s "${HOME}/.zshrc_private" ]]; then
  source "${HOME}/.zshrc_private"
fi
